# vim:fileencoding=utf-8:foldmethod=marker
# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME
background #0f1511
tab_bar_background #0f1511
hide_window_decorations yes
mouse_hide_wait 1.0
background_opacity 0.9
window_padding_width 0 10
cursor none
remember_window_size no
initial_window_width 700
enable_audio_bell no
tab_bar_style powerline
tab_title_template "{title[title.rfind(':')+1:]}"
active_tab_font_style   bold
inactive_tab_font_style normal

# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size 19
modify_font underline_position 1
modify_font underline_thickness 150%
modify_font strikethrough_position 2px

enabled_layouts fat:bias=75;full_size=1;mirrored=true, stack
active_border_color #4e6866
